### ISSUE TITLE
Multipart POST request trough tor agent fails

### ISSUE THREAD

**Issue by NachoCheeseDip** [danielstjules/toragent#2]
Im trying to upload image using multipart/form-data POST request trough Toragent. The image size is 58 735 bytes. If i comment   'agent: toragentInstance,' option, the file is uploaded fine. But if i do it trought tor i get the following error:

code : ECONNRESET

> Error: socket hang up
>     at createHangUpError (_http_client.js:302:15)
>     at Socks5ClientSocket.socketOnEnd (_http_client.js:394:23)
>     at emitNone (events.js:86:13)
>     at Socks5ClientSocket.emit (events.js:188:7)
>     at TLSSocket.<anonymous> (/home/user/site/node_modules/socks5-client/lib/Socket.js:129:8)
>     at emitNone (events.js:91:20)
>     at TLSSocket.emit (events.js:188:7)
>     at endReadableNT (_stream_readable.js:975:12)
>     at _combinedTickCallback (internal/process/next_tick.js:80:11)
>     at process._tickCallback (internal/process/next_tick.js:104:9)

Here is the code:

```
 var formData = {
        photo: {
            value: fs.createReadStream(file),
            options: {
                filename: path.basename(file)
            }
        }
    };

var headers = {
       'User-Agent': params.userAgent,
       'Accept-Encoding' : 'gzip, deflate',
       'Connection': 'keep-alive'
};
var options = {

        encoding: null,
        followAllRedirects: false,
        method : "POST",
        headers : headers,
        agent: toragentInstance,
        formData : formData,
        timeout : 1200000,
        strictSSL: false,
};

let httpResponse = await request(options);
```

I tried to solve this, by switching on keepAlive option of the Toragent inherited http.Agent  after the creation of toragent instance:

```
  TorAgent.create(false, function (tor_err, agent) {
            agent.keepAlive = true;
  }
```
So if i switch it on, i get another error:

_http_agent.js:74
          socket.unref();
                 ^

> 
> TypeError: socket.unref is not a function
>     at TorAgent.<anonymous> (_http_agent.js:74:18)
>     at emitTwo (events.js:106:13)
>     at TorAgent.emit (events.js:194:7)
>     at Socks5ClientSocket.onFree (_http_agent.js:217:11)
>     at emitNone (events.js:86:13)
>     at Socks5ClientSocket.emit (events.js:188:7)
>     at emitFreeNT (_http_client.js:579:10)
>     at _combinedTickCallback (internal/process/next_tick.js:77:11)
>     at process._tickCallback (internal/process/next_tick.js:104:9)

What can be wrong here?

**Comment by danielstjules** [comment]
Sorry for the late reply! Is it possible the target host is blocking tor exit nodes and simply closing the socket? Were you able to resolve this issue?
