### ISSUE TITLE
Windows anyone?

### ISSUE THREAD

**Issue by knoxcard** [danielstjules/toragent#5]
Does this work with Windows?  I am getting an empty output here...

var TorAgent = require('toragent');
var request  = require('request');
TorAgent.create(false).then((agent) => {
  // Spawning Tor
  // Tor spawned with pid 42776 listening on 55683

  console.log('spawn tor!'.blue)
})

**Comment by knoxcard** [comment]
Got it to work in Linux, I am sure I could get it to work with Windows by including Tor.exe.  If I get around to it and get it done I will push up the code.

**Comment by danielstjules** [comment]
Sorry, I don't currently have a windows machine to test on, but would welcome a PR!
